label: Contenido
description: 'Encontrar y administrar contenido.'
display:
  default:
    display_options:
      exposed_form:
        options:
          submit_button: Filtro
          reset_button_label: Restablecer
          exposed_sorts_label: 'Ordenar por'
      pager:
        options:
          tags:
            previous: '‹ Anterior'
            next: 'Siguiente >'
            first: '« Primero'
            last: 'Último »'
      fields:
        title:
          label: Título
        type:
          label: 'Tipo de contenido'
      filters:
        title:
          expose:
            label: Título
        type:
          expose:
            label: 'Tipo de contenido'
        status:
          expose:
            label: Estado
          group_info:
            label: 'Estado de publicación'
            group_items:
              1:
                title: Publicado
              2:
                title: 'Sin publicar'
        langcode:
          expose:
            label: Language
      title: Contenido
      empty:
        area_text_custom:
          content: 'No hay contenido disponible.'
    display_title: Máster
