label: Contenu
description: 'Trouver et gérer le contenu.'
display:
  default:
    display_options:
      exposed_form:
        options:
          submit_button: Filtrer
          reset_button_label: Réinitialiser
          exposed_sorts_label: 'Trier par'
      pager:
        options:
          tags:
            previous: '‹ Précédent'
            next: 'Suivant ›'
            first: '« Premier'
            last: 'Dernier »'
      fields:
        title:
          label: Titre
        type:
          label: 'Type de contenu'
        changed:
          label: 'Mis à jour'
      filters:
        title:
          expose:
            label: Titre
        type:
          expose:
            label: 'Type de contenu'
        status:
          expose:
            label: État
          group_info:
            label: 'Statut de publication'
            group_items:
              1:
                title: Publié
              2:
                title: 'Non publié'
        langcode:
          expose:
            label: Language
      title: Contenu
      empty:
        area_text_custom:
          content: 'Aucun contenu disponible.'
    display_title: Maître
