_core:
  default_config_hash: yXadRE77Va-G6dxhd2kPYapAvbnSvTF6hO4oXiOEynI
langcode: en
uuid: e5583f2f-7993-43cd-9d5c-895547809715
name: 'Global Humanitarian Overview'
mail: admin@gho.unocha.org
slogan: ''
page:
  403: ''
  404: ''
  front: /node/1
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
